### ISSUE TITLE
V3 Roadmap

### ISSUE THREAD

**Issue by frenic** [frenic/glitz#4]
- [x] Change React peer dependency to 16.8
- [x] Use React Hooks for Glitz instance
- [x] Use React Hooks for theme
- [x] Replace `innerRef` prop with `React.forwardRef`
